# Generated by Django 2.2 on 2021-01-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_prodile',
            new_name='user_profile',
        ),
    ]
